blank_issues_enabled: true
contact_links:
    - name: Urgent issue
      url: https://www.linkedin.com/in/adhityan
      about: If your issue is urgent and needs immidiately attention, please contact the author directly on LinkedIn.
